# Generated by Django 5.0.7 on 2024-07-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lostandfound",
            "0003_remove_founditem_description_remove_founditem_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lostitem",
            name="brand",
            field=models.CharField(max_length=50),
        ),
    ]
