# Generated by Django 5.0.7 on 2024-07-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lostandfound", "0006_alter_founditem_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founditem",
            name="brand",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
